### ISSUE TITLE
Feature - Translate all ObjectID fields

### ISSUE THREAD

**Issue by crobinson42** [js-data/js-data-mongodb#16]
There are cases where someone may implement `js-data-mongodb` towards a pre existing Mongo database collection and some libraries (ORM's) that perform relational mapping store record _id's in the `ObjectID` bson value, ie: `{ "_bsontype": "ObjectID", "id": { "type": "Buffer", "data": [87,...156] } }`. 

When using `js-data-mongodb`, it would be convenient to pass an option to translate all ObjectID fields to a string.

I would apply the logic in the method `_translateIds()` on line 218 and change the name and all references to it to "`_translateObjectIDs()`".

@jmdobry If you'll accept this feature, I'll put in a PR. Please let me know.

**Comment by crobinson42** [comment]
*re version 1.0.0-beta.1

**Comment by jmdobry** [comment]
This will be an option where users can opt in? No breaking change?

**Comment by crobinson42** [comment]
Yes.

**Comment by jmdobry** [comment]
And how is this different than the [translateId option](http://api.js-data.io/js-data-mongodb/latest/MongoDBAdapter.html#translateId)? It works in the reverse?

**Comment by crobinson42** [comment]
It would use the same logic inside `translateId` but for the sake of DRY code, I propose renaming `translateId` to `translateObjectIDs` and then running the `if...` logic on the `jsDataOpts`.

**Comment by jmdobry** [comment]
Renaming an option is a breaking change. Let's see your PR.
