### ISSUE TITLE
Default conversion _id to id 

### ISSUE THREAD

**Issue by crobinson42** [js-data/js-data-mongodb#21]
>  // Why couldn't Mongo just use "id"?

No shit?! 

@jmdobry How do you feel about making default functionality to convert `id` to `_id` and vica versa with adapter interactions?

We can still have the config `idAttribute` property to be specified for override.

**Comment by jmdobry** [comment]
Hmm. 

| Pros | Cons |
| --- | --- |
| Saves users from having to set `idAttribute` to `_id` in `mapperDefaults` | The JSData schema will be slightly out of sync with how the data is stored. `id` vs `_id` |
| `id` is prettier than `_id` | Might be surprising for users, as the rest of their app might already be using `_id`, and most MongoDB users know the pk field is `_id` |
| Might make it easier to combine the mongo adapter with other adapters that don't expect `_id` | Could make debugging a little more difficult? |

I think in the end, this might violate the Principle of Least Astonishment. It's simple enough to do

``` js
new Container({
  mapperDefaults: {
    idAttribute: '_id'
  }
})
```

I might be okay with adding an option that translates `id` to `_id` and visaversa, but I think it should be disabled by default.

This also raises the question of whether JSData's `Mapper` class should have some better facilities for mapping fields in memory to different fields in the database. i.e. camelCase to snake_case, `id` to `_id`, etc.

**Comment by crobinson42** [comment]
Understood. I'll put together a PR that at least makes it an option to convert in the adapter - leaving the default behavior as-is.

**Comment by crobinson42** [comment]
@jmdobry I'm sure you can point out improvements.. but this is the general idea #29
