### ISSUE TITLE
Add suport for the '==' operator shorthand 

### ISSUE THREAD

**Issue by oliverhr** [js-data/js-data-mongodb#22]
This work fine:

```
User.findAll({
  where: {
    field: {
      '==': '393fe308fc3d796b6b80c548ceeac69008a68a09'
    }
  }
})
...
User.findAll({
    field: {
      '==': '393fe308fc3d796b6b80c548ceeac69008a68a09'
    }
})
...
User.findAll({
    field: '393fe308fc3d796b6b80c548ceeac69008a68a09'
})
```

But this **not**:

```
User.findAll({
  where: {
    field: '393fe308fc3d796b6b80c548ceeac69008a68a09'
  }
})
```

**Comment by crobinson42** [comment]
Try:

```
User.findAll({ field: '393fe308fc3d796b6b80c548ceeac69008a68a09' })
```

**Comment by oliverhr** [comment]
Thanks @crobinson42, I mention that way as the 3rd point, the thing is, the query syntax documentation samples use `where`, Because of that, is common to have code like this:

```
User.findAll({
  where: {
    fieldA: 'c548ceeac69008a68a09',
    fieldB: '393fe308fc3d796b6b80c',
    fieldC: {
      '>': 10,
    },
  }
})
```

And I think it shuold be supported in the MongoDB adapter.

**Comment by jmdobry** [comment]
As far as I can tell, this already works. Here is the relevant code: https://github.com/js-data/js-data-mongodb/blob/master/src/index.js#L792

I just ran a query like this:

``` js
store.findAll('user', {
  where: {
    foo: 'bar'
  }
})
```

and it got translated to this:

``` js
store.findAll('user', {
  where: {
    foo: {
      '==': 'bar'
    }
  }
})
```

@oliverhr What version of `js-data-mongodb` are you using?

**Comment by oliverhr** [comment]
js-data: 2.9.0
js-data-mongodb: 0.7.0

**Comment by jmdobry** [comment]
Ah, I tested it with js-data 3.0.0-rc.4 and js-data-mongodb 1.0.0-rc.1

**Comment by crobinson42** [comment]
@oliverhr I'm going to close this issue as it's related to v2.x and we're focusing features on v3.x and this use case is supported in v3.x. You're welcome to submit PR with this functionality on the 2.x branch.

_edit: re version numbers, I'm referencing `js-data`, not v2.x/3.x of `js-data-mongodb`_
