### ISSUE TITLE
Remove subdocument (atomic update)

### ISSUE THREAD

**Issue by nhim175** [js-data/js-data-mongodb#34]
## Description

versions:

js-data: 2.10.0
js-data-mongodb: 0.7.0

## Steps to reproduce

- Define `User` resource model
- Assume that a user data:
`{
  _id: 'XXXX',
  groups: {
    groupOne: true,
    groupTwo: true
  }
}`
- Do: `User.update('XXXX', {groups: {groupOne: null}})`
- Expected result: `groupOne` gets removed from `groups`
- End result: `groups` was overridden and become `groups: {groupOne: null}`

If there's no way to do atomic update, the code won't scale.

Thanks!

**Comment by jmdobry** [comment]
@crobinson42 Can you take a look?

**Comment by oliverhr** [comment]
To update an inner element the right syntax is:

```
User.update('XXXX', { 'groups.groupOne': null });
```
But the problem still If you set the value to `undefined` or `null` the element remain in the object, so after update you get:

```
{ _id: 'XXXX', groups: { groupOne: null, groupTwo: true } }
```

So the question is how remove a property from an object?

Tested with:
js-data: `2.9.0`, `2.10.0`
js-data-mongodb: `0.7.0`

**Comment by crobinson42** [comment]
We've addressed this in #32 for v1. 

I wonder if we make this same fix for v0.x it will break existing code/implementations. Thoughts?

**Comment by jmdobry** [comment]
0.7.0 is pre-1.0.0, so a breaking change would bump it to 0.8.0

**Comment by crobinson42** [comment]
stale

**Comment by nhim175** [comment]
Thanks everyone for supporting me on this 🙏🏻
