### ISSUE TITLE
hasOne relation inconsistent return

### ISSUE THREAD

**Issue by oliverhr** [js-data/js-data-mongodb#36]
## "hasOne" relation inconsistent return

hasOne relationship is a one to one relation, when a related item exists the `OBJECT` is returned, but if the related item does not exists on the related collection and empty `ARRAY` is returned.

I think the query should return an `empty object` or better yet `undefined`.

js-data: 2.10
js-data-mongo: 0.7.0

Thanks!

**Comment by crobinson42** [comment]
stale
