### ISSUE TITLE
Missing 0.7.0

### ISSUE THREAD

**Issue by oliverhr** [js-data/js-data-mongodb#38]
## Missing tag for 0.7.0

Please create a tag on commit - `af5c2dc0ff1b72a1f2a82ce1d09e9c4f7d773d28` for tag 0.7.0

Assuming that 0.7.0 was the last version that work with js-data v2, and its a version published on npm.

Thanks!

**Comment by crobinson42** [comment]
https://github.com/js-data/js-data-mongodb/tree/0.7.0

**Comment by oliverhr** [comment]
thank you @crobinson42
