### ISSUE TITLE
support for 2.x driver and ObjectIds

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data-mongodb#8]
See js-data/js-data#110

**Comment by jmdobry** [comment]
@marklawlor let me know if 0.2.3 works better for you

**Comment by marklawlor** [comment]
DS#Create now correctly returns the created object with mongo 2.6.x and 3.0.x

DS#Find / DS#Get still don't work with ObjectID hashs. If you pass the ObjectID object [it will be caught and rejected by js-data](https://github.com/js-data/js-data/blob/master/src/datastore/async_methods/find.js#L11) and if you pass the hash as a string the mongo adapter will compare the the _id using a string, not an ObjectID.

**Comment by jmdobry** [comment]
> if you pass the hash as a string the mongo adapter will compare the the _id using a string, not an ObjectID

Can you explain this more? Does this mean that the mongo server doesn't treat an ObjectId and its hash the same? They're not interchangeable?

**Comment by marklawlor** [comment]
Thats correct, try this in the mongo cli with test being your table name

```
db.test.insert({ name: 'john' });
db.test.find(); // 1 result

db.test.insert({ _id: <ObjectID hash of john > ,name: 'bob' });
db.test.find(); // 2 results

db.test.find({ _id: ObjectID( <hash string> ) }) // John
db.test.find({ _id: <hash string> }) // Bob
```

An ObjectID's hash is simply a readable representation of its BSON data, not an interchangeable value.
